build:
    environment:
        php:
            version: "8.1"
    nodes:
        coverage:
            tests:
                override:
                    - command: XDEBUG_MODE=coverage ./vendor/bin/phpunit --coverage-clover build/coverage-clover.xml tests
                      coverage:
                        file: build/coverage-clover.xml
                        format: clover
filter:
    paths:
        - 'src/'
tools:
    php_mess_detector:
        enabled: true
        filter:
            paths:
                - 'src/'
    php_code_sniffer:
        enabled: false
    php_pdepend:
        enabled: true
        configuration_file: null
        suffixes:
            - php
        excluded_dirs: {  }
        filter:
            paths:
                - 'src/'
    php_analyzer:
        enabled: true
        extensions:
            - php
        filter:
            paths:
                - 'src/'
        path_configs: {  }
    php_changetracking:
        enabled: true
        bug_patterns:
            - '\bfix(?:es|ed)?\b'
        feature_patterns:
            - '\badd(?:s|ed)?\b'
            - '\bimplement(?:s|ed)?\b'
        filter:
            paths:
                - 'src/'
    php_loc:
        enabled: true
        excluded_dirs:
            - 'vendor/*'
            - 'tests/*'
    php_cpd:
        enabled: true
        excluded_dirs: {  }
        filter:
            paths:
                - 'src/'
